---
title: "Data Exploration and Visualization"
output: html_notebook
---

#Loading the libraries

```{r echo=TRUE}
library(tidyverse)
library(sf)
library(rnaturalearth)
library(countrycode)
library(ggrepel)
library(plm)
library(broom)
library(fixest)
```



```{r}
df <- read.csv('owid-energy-data.csv')
View(df)
```


```{r}

list_of_countries <- df %>% 
  group_by(country) %>% 
  summarise(total_emissions = sum(greenhouse_gas_emissions, na.rm = TRUE)) %>% 
  arrange(desc(total_emissions)) %>% 
  filter(total_emissions > 100) %>% 
  distinct(country) %>% 
  filter(!country %in% c('World',
                         'G20 (Ember)',
                         'Asia',
                         'Asia (Ember)',
                         'High-income countries',
                         'Upper-middle-income countries',
                         'OECD (Ember)',
                         'G7 (Ember)',
                         'North America',
                         'North America (Ember)',
                         'Europe (Ember)',
                         'Europe',
                         'Lower-middle-income countries',
                         'European Union (27)',
                         'Middle East (Ember)',
                         'ASEAN (Ember)',
                         'Latin America and Caribbean (Ember)',
                         'Africa (Ember)',
                         'Africa',
                         'South America',
                         'Oceania (Ember)',
                         'Oceania',
                         'Low-income countries',
                         'Hong Kong')) %>% 
  pull(country)
```

```{r}
list_of_countries
world <- ne_countries(scale = 'small', returnclass = 'sf')

world

#combine the data
countries_to_select <- 
  world %>% 
  select(geometry, name, iso_a3) %>% 
  left_join(df %>% 
              filter(country %in% list_of_countries) %>% 
              select(country, iso_code) %>% 
              mutate(visited = TRUE), by = c('iso_a3' = 'iso_code'))

countries_to_select
world %>% 
  filter(admin != 'Antarctica') %>% 
  st_transform(crs = '+proj=robin') %>% 
  ggplot() +
  geom_sf(color = 'darkgrey') +
  geom_sf(data = countries_to_select, aes(fill = visited)) +
  scale_fill_manual(values = 'royalblue') +
  theme_void() +
  labs(title = 'Top 60 Carbon Intensive Countries',
       x = NULL,
       y = NULL) +
  theme(plot.title = element_text(face = 'bold'),
        axis.text.x = element_blank(),
        legend.position = 'none',
        plot.caption = element_text(hjust = 0))


```

```{r, fig.width=8}
#countries with the highest emissions
#need to be completed


df %>% 
  filter(country %in% list_of_countries) %>% 
  select(country, year, greenhouse_gas_emissions, population, gdp) %>% 
  filter(year >= 1990) %>% 
  group_by(country) %>% 
  summarize(total_emissions = sum(greenhouse_gas_emissions, na.rm = TRUE),
            total_population = mean(population)) %>% 
  arrange(desc(total_emissions)) %>% 
  filter(total_emissions >= 1000) %>% 
  ggplot(aes(x = reorder(country, total_emissions), y = total_emissions, fill = total_population)) +
  geom_bar(stat = 'identity', width = 0.9) +
  geom_text(aes(label = total_emissions), hjust = -0.3, size = 3.5) +
  coord_flip() +
  scale_y_discrete(expand = c(0.01, 0.01)) +
  theme_minimal() +
  theme(panel.grid.major = element_blank())
```


```{r}
library(tidyverse)
ultimate_df %>% 
  group_by(country) %>% 
  summarize(total_capita = mean(co2_emissions_per_capita)) %>% 
  arrange(desc(total_capita)) %>% 
  ggplot(aes(x = reorder(country, total_capita), y = total_capita)) +
  geom_bar(stat = 'identity', size = 0.7, fill = "#80aaff") +
  coord_flip() +
  theme_minimal() +
  theme(panel.grid.major = element_blank()) +
  scale_y_continuous(expand = expansion(mult = c(0.01, 0.05))) +
  geom_label(aes(label = round(total_capita,0), 
                hjust = 1.2, 
                nudge_x = -.2, 
                family = "Arial",
                label.size = 0,
                face = 'bold')) +
  theme(
    axis.text.y = element_text(size = 10, family = 'Arial', face = 'bold'),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    plot.title = element_text(family = "Times", size = 16, face = "bold"),
    plot.subtitle = element_text(family = "Arial", size = 12, face = "italic"),
    panel.grid.minor = element_blank()
  ) +
  labs(title = 'Average CO2 emissions per capita',
       subtitle = 'The quantity is expressed in Metric Tonnes')

ultimate_df %>% 
  filter(country == 'India')
ultimate_df

ultimate_df %>% 
  group_by(country) %>% 
  summarize(total = sum(co2_emissions_kt)) %>%
  arrange(desc(total)) %>%
  mutate(total = (total * 1000) / 1000000000) %>% 
  slice(1:10) %>%
  ggplot(aes(x = reorder(country, total), y = total)) +
  geom_bar(stat = 'identity', width = 0.9, fill = "#ff9966") +
  coord_flip() +
  theme_minimal() +
  theme(panel.grid.major = element_blank()) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  theme(panel.grid.major = element_blank()) +
  scale_y_continuous(expand = expansion(mult = c(0.01, 0.05))) +
  geom_label(aes(label = round(total,0), 
                hjust = 1.2, 
                nudge_x = -.2, 
                family = "Arial",
                label.size = 0,
                face = 'bold')) +
  theme(
    axis.text.y = element_text(size = 10, family = 'Arial', face = 'bold'),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    plot.title = element_text(family = "Times", size = 16, face = "bold"),
    plot.subtitle = element_text(family = "Arial", size = 12, face = "italic"),
    panel.grid.minor = element_blank()
  ) +
  labs(title = 'Total greenhouse gas emissions from 1990 to 2022',
       subtitle = 'The quantity is expressed in kilotonnes.')

ggsave("total_emissions.png", plot = p2, width = 10, height = 6)
```

```{r}
power_plants <- read.csv('global_power_plant_database.csv')

t1 <- world %>% 
  select(geometry, name, iso_a3) %>% 
  left_join(power_plants %>% 
            filter(primary_fuel %in% c('Hydro', 'Solar', 'Wind', 'Biomass', 'Wave and Tidal', 'Geothermal')) %>% 
            group_by(country_long, country, primary_fuel) %>% 
            summarize(total = sum(capacity_mw), .groups = 'drop') %>% 
            slice_max(total, by = country_long, with_ties = FALSE) %>% 
            arrange(country_long, primary_fuel) %>% 
            mutate(primary_fuel = ifelse(country_long == 'Antarctica', NA, primary_fuel)), 
            
            by = c('iso_a3' = 'country'))

t1 %>% filter(name == 'Antarctica')


world %>% 
  st_transform(crs = '+proj=robin') %>% 
  ggplot() +
  geom_sf(color = 'black') +
  geom_sf(data = t1, aes(fill = primary_fuel)) +
  scale_fill_manual(values = c('#00ff99', '#ff6666', '#3399ff', '#ffff66', '#ff9900'), na.value = 'grey50') +
  theme_void() +
  labs(x = 'dfdsfds', 
       subtitle = 'dsfsdfsdf') +
  theme(plot.title = element_text(face = 'bold'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        plot.caption = element_text(hjust = 0),
        panel.background = element_rect(fill = "aliceblue"))
  
world <- world %>% 
  mutate(iso_a3 = ifelse(name == 'Norway', 'NOR', iso_a3),
         iso_a3 = ifelse(name == 'France', 'FRA', iso_a3))

ggsave("energy_map.png", width = 10, height = 10, dpi = "screen")




```

